In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv


In [4]:
df=pd.read_csv('/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [5]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
df.shape

(10000, 14)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
#check duplicate rows 
df.duplicated().sum()

0

In [9]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [10]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [11]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [12]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [13]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [14]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [15]:
from sklearn.model_selection import train_test_split 

In [16]:
X=df.drop(['Exited'],axis=1)
Y=df['Exited']

In [17]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [18]:
X_train

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
8856          774   26       5       0.00              2          1   
1545          602   42       6  158414.85              1          1   
8136          716   38       1       0.00              2          1   
7768          601   20       9  122446.61              2          1   
7782          585   54       8   87105.32              1          1   
...           ...  ...     ...        ...            ...        ...   
1099          494   38       7       0.00              2          1   
2514          592   26       4  105082.07              2          1   
6637          850   36       3       0.00              2          1   
2575          551   54       5  102994.04              1          1   
7336          654   28       7       0.00              2          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
8856               1         64716.08                  0                0   
1545               1        131886.46                  1                0   
8136               1         99661.46                  0                0   
7768               0         86791.90                  0                1   
7782               1         55346.14                  0                0   
...              ...              ...                ...              ...   
1099               1          6203.66                  0                1   
2514               0        132801.57                  1                0   
6637               0        195033.07                  0                0   
2575               0        176680.16                  1                0   
7336               0        151316.37                  0                0   

      Gender_Male  
8856            0  
1545            0  
8136            0  
7768            0  
7782            1  
...           ...  
1099            1  
2514            0  
6637            1  
2575            1  
7336            0  

[8000 rows x 11 columns]

In [19]:
Y_train

8856    0
1545    0
8136    0
7768    0
7782    0
       ..
1099    0
2514    0
6637    0
2575    1
7336    0
Name: Exited, Length: 8000, dtype: int64

In [20]:
X_test

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
7878          731   38      10  123711.73              2          1   
3224          645   41       2  138881.04              1          1   
1919          618   56       7       0.00              1          1   
4432          621   33       4       0.00              2          1   
4835          561   34       4   85141.79              2          1   
...           ...  ...     ...        ...            ...        ...   
9073          702   60       5  138597.54              2          1   
8584          731   19       6       0.00              2          1   
5390          735   38       1       0.00              3          0   
5092          688   39       0       0.00              2          1   
2964          721   46       1  115764.32              2          0   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
7878               0        171340.68                  0                0   
3224               0        129936.53                  1                0   
1919               1        142400.27                  0                0   
4432               1         40299.23                  0                1   
4835               1         29217.37                  0                1   
...              ...              ...                ...              ...   
9073               1         41536.59                  1                0   
8584               1        151581.79                  0                0   
5390               0         92220.12                  0                0   
5092               0         53222.15                  0                0   
2964               0        102950.79                  0                0   

      Gender_Male  
7878            0  
3224            0  
1919            1  
4432            1  
4835            1  
...           ...  
9073            0  
8584            1  
5390            0  
5092            0  
2964            1  

[2000 rows x 11 columns]

In [21]:
Y_test

7878    1
3224    1
1919    1
4432    0
4835    0
       ..
9073    1
8584    0
5390    1
5092    1
2964    0
Name: Exited, Length: 2000, dtype: int64

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()

In [24]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [25]:
X_train_scaled

array([[ 1.27754581, -1.23264342, -0.012743  , ..., -0.58408625,
        -0.57138416, -1.0862028 ],
       [-0.49959477,  0.28410615,  0.33282985, ...,  1.71207591,
        -0.57138416, -1.0862028 ],
       [ 0.67827747, -0.09508124, -1.39503438, ..., -0.58408625,
        -0.57138416, -1.0862028 ],
       ...,
       [ 2.06279398, -0.28467494, -0.70388869, ..., -0.58408625,
        -0.57138416,  0.9206384 ],
       [-1.02653762,  1.42166833, -0.012743  , ...,  1.71207591,
        -0.57138416,  0.9206384 ],
       [ 0.03768029, -1.04304972,  0.67840269, ..., -0.58408625,
        -0.57138416, -1.0862028 ]])

In [26]:
X_test_scaled

array([[ 8.33260665e-01, -9.50812388e-02,  1.71512123e+00, ...,
        -5.84086250e-01, -5.71384156e-01, -1.08620280e+00],
       [-5.53096261e-02,  1.89309306e-01, -1.04946154e+00, ...,
         1.71207591e+00, -5.71384156e-01, -1.08620280e+00],
       [-3.34279369e-01,  1.61126203e+00,  6.78402693e-01, ...,
        -5.84086250e-01, -5.71384156e-01,  9.20638397e-01],
       ...,
       [ 8.74589516e-01, -9.50812388e-02, -1.39503438e+00, ...,
        -5.84086250e-01, -5.71384156e-01, -1.08620280e+00],
       [ 3.88975520e-01, -2.84390545e-04, -1.74060723e+00, ...,
        -5.84086250e-01, -5.71384156e-01, -1.08620280e+00],
       [ 7.29938538e-01,  6.63293547e-01, -1.39503438e+00, ...,
        -5.84086250e-01, -5.71384156e-01,  9.20638397e-01]])

In [27]:
 import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [32]:
model= Sequential()
model.add(Dense(3,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

In [33]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 3)                 36        
                                                                 
 dense_3 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [34]:
#model complilation stage
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [45]:
model.fit(X_train_scaled,Y_train,epochs=1000)

Epoch 1/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4277
Epoch 2/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4254
Epoch 3/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4233
Epoch 4/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4213
Epoch 5/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4195
Epoch 6/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4178
Epoch 7/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4162
Epoch 8/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4148
Epoch 9/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4134
Epoch 10/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4123
Epoch 11/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4110
Epoch 12/1000
250/250 [==============================] - 0s 1ms/step - loss: 0.4099
E

In [46]:
model.layers[0].get_weights()

[array([[ 7.50507414e-02,  2.56450698e-02, -1.16422884e-02],
        [-2.07271934e+00,  1.50643396e+00,  2.77168453e-01],
        [ 1.51125640e-02,  2.92734295e-01,  7.47299269e-02],
        [ 4.55586016e-01,  2.92409927e-01, -8.09453368e-01],
        [-3.27872217e-01,  6.79992104e+00, -1.89619279e+00],
        [-6.14111982e-02,  2.47499272e-01,  1.04882605e-01],
        [-2.48725489e-02,  1.91812360e+00,  3.79625946e-01],
        [-1.77898314e-02,  1.59032494e-02, -2.77114031e-03],
        [-5.40939391e-01, -3.97480011e-01,  2.52738416e-01],
        [ 1.41030671e-02,  2.12705821e-01, -1.43801004e-01],
        [ 1.95239961e-01,  1.97200507e-01,  1.74984336e-01]], dtype=float32),
 array([0.4808821, 1.9094852, 2.5587392], dtype=float32)]

In [47]:
Y_log=model.predict(X_test_scaled)

63/63 [==============================] - 0s 971us/step


In [48]:
y_pred=np.where(Y_log>0.5,1,0)

In [49]:
from sklearn.metrics import accuracy_score

In [50]:
accuracy_score(Y_test,y_pred)

0.857